<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>6870d1a4-c9aa-4452-80eb-8872794e01f4</UserSecretsId>
	<PackageId>IndieGames.Infrastructure</PackageId>
	<Version>0.1.59</Version>
	<Authors>NotS1mp</Authors>
	<RepositoryUrl>https://github.com/XShine555/IndieGames-AspNet</RepositoryUrl>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="global-bundle.pem" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.S3" Version="4.0.21.1" />
    <PackageReference Include="MassTransit" Version="8.5.9" />
    <PackageReference Include="MassTransit.AmazonSQS" Version="8.5.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.6" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.6">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.6" />
    <PackageReference Include="Microsoft.Extensions.Configuration.FileExtensions" Version="10.0.6" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.6" />
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="10.0.6" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.6" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="10.0.6" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.6" />
    <PackageReference Include="Microsoft.Extensions.Options.DataAnnotations" Version="10.0.6" />
    <PackageReference Include="MimeMapping" Version="4.0.0" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.1" />
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Application\Application.csproj" />
    <ProjectReference Include="..\Domain\Domain.csproj" />
  </ItemGroup>

</Project>
